
/*  
    CSCI 585  HOMEWORK-3
    
    NAME  : AVINASH AKKA
    USC ID: 3874-5774-01

 --DELETES THE DATABASE CREATED--

*/



DROP INDEX STUDENT_IDX;
DELETE from  USER_SDO_GEOM_METADATA where TABLE_NAME='STUDENT';
DROP TABLE STUDENT;

DROP INDEX BUILDING_IDX;
DELETE from  USER_SDO_GEOM_METADATA where TABLE_NAME='BUILDING';
DROP TABLE BUILDING;

DROP INDEX TRAMSTOP_IDX;
DELETE from  USER_SDO_GEOM_METADATA where TABLE_NAME='TRAMSTOP';
DROP TABLE TRAMSTOP;





